<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
          integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link href="../../css/homepage.css" rel="stylesheet">
    <title>TITLE</title>
    <script defer src="../../js/homepage.js"></script>
</head>

<body>
<nav>
    <a href="/films" class="nav-links">Home</a>
    <a id="add-film-button" class="nav-links">Add film</a>
</nav>
<div id="add-film-container">
    <dialog id="search-films-modal">
        <p class="search-header">Search films database</p>
        <div id="film-search-form-container">
            <form id="search-tmdb-form">
                <input id="search-films-input" type="text">
                <input id="search-films-submit" type="submit"/>
                <button id="close-search-films-modal">Close</button>
            </form>
        </div>
        <div id="pagination-anchor"></div>
        <div id="search-results-container"></div>
    </dialog>
</div>
<div class="header-background">
    <header>
        <h1>Reels from the Crypt</h1>
        <h2>a film collection</h2>
    </header>
</div>

<div id="collection-display">
    <?php
    foreach ($films as $film) {
        echo '<div class="film">';
        echo '<img src="' . $film['poster_path'] . '" alt="' . $film['title'] . '" class="film-poster">';
//    echo '<h3 class="film-title">' . $film['title'] . ' (' . substr($film['release_date'], 0, 4) . ')</h3>';
//    echo '<h4 class="film-director">Dir: ';
//    $directors = html_entity_decode($film['director']);
//    echo implode(", ", json_decode($directors));
//    echo '</h4>';
        echo '</div>';
    }
    ?>

</div>

<footer>
    <!--    Attribute TMDB here, any other info-->
</footer>

</body>

</html>