<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="style.css" rel="stylesheet">
    <title>TITLE</title>
</head>

<body>

<h1>This is a test</h1>
<?php

$keys = array_keys($films[0]);

$testFilm = $films[12];

foreach ($keys as $key) {
    echo $key . "<br>";
}

$testCastList = $testFilm['cast'];

$testCastArray = unserialize($testCastList);

foreach ($testCastArray as $cast) {
    echo $cast . "<br>";
}

?>

</body>

</html>