<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="style.css" rel="stylesheet">
    <title>TITLE</title>
</head>

<body>

<h1>Reels from the Crypt</h1>

<form method="get">
    <label for="searchTerm">Search</label>
    <input id="searchTerm" type="text" name="searchTerm">
    <input type="submit">
</form>

<?php
if (isset($_GET['searchTerm'])) {
    $thing =  $_GET['searchTerm'];
}
?>

</body>

</html>